from dataclasses import dataclass
from pathlib import Path

from kneevision.rag.corpus import GuidelineChunk
from kneevision.rag.retriever import GuidelineRetriever
from kneevision.rag.llm import OllamaClient, OllamaUnavailableError

DISCLAIMER = (
    "This is an educational summary generated by a research demo project, "
    "not medical advice. It has not been reviewed by a clinician. Always "
    "consult a qualified healthcare professional for actual diagnosis and care."
)

KL_LABELS = {0: "Normal", 1: "Doubtful", 2: "Mild", 3: "Moderate", 4: "Severe"}


@dataclass
class RehabRecommendation:
    kl_grade: int
    retrieved_chunks: list[GuidelineChunk]
    synthesis: str  # LLM-written summary, or a retrieval-only fallback if the LLM is unavailable
    used_llm: bool
    disclaimer: str = DISCLAIMER


class RehabRecommender:
    """Retrieval-augmented rehab guidance: retrieves relevant guideline
    excerpts for a KL grade (+ optional patient context), then asks a local
    LLM to synthesize them into a short, readable summary. Falls back to a
    plain concatenation of the retrieved excerpts if the LLM is unavailable,
    so the pipeline degrades gracefully rather than failing outright.
    """

    def __init__(self, retriever: GuidelineRetriever, llm: OllamaClient | None = None):
        self.retriever = retriever
        self.llm = llm or OllamaClient()

    @classmethod
    def from_guidelines_dir(cls, guidelines_dir: Path, llm: OllamaClient | None = None) -> "RehabRecommender":
        return cls(GuidelineRetriever.from_dir(guidelines_dir), llm=llm)

    def recommend(self, kl_grade: int, patient_context: str = "", top_k: int = 4) -> RehabRecommendation:
        if not 0 <= kl_grade <= 4:
            raise ValueError(f"kl_grade must be 0-4, got {kl_grade}")

        query = f"knee osteoarthritis KL grade {kl_grade} ({KL_LABELS[kl_grade]}) rehabilitation. {patient_context}".strip()
        chunks = self.retriever.retrieve(query, kl_grade=kl_grade, top_k=top_k)

        try:
            synthesis = self.llm.generate(self._build_prompt(kl_grade, patient_context, chunks))
            used_llm = True
        except OllamaUnavailableError:
            synthesis = self._fallback_synthesis(chunks)
            used_llm = False

        return RehabRecommendation(
            kl_grade=kl_grade, retrieved_chunks=chunks, synthesis=synthesis, used_llm=used_llm,
        )

    def _build_prompt(self, kl_grade: int, patient_context: str, chunks: list[GuidelineChunk]) -> str:
        excerpts = "\n\n".join(f"[{c.heading} — {c.source_path}]\n{c.text}" for c in chunks)
        context_line = f"Patient context: {patient_context}\n" if patient_context else ""
        return (
            "You are summarizing clinical guideline excerpts into a short, clear rehabilitation "
            "suggestion for a knee osteoarthritis patient. Use ONLY the excerpts below — do not add "
            "any medical claims not supported by them. Keep it to 4-6 sentences. End by stating this "
            "is not medical advice and a clinician should be consulted.\n\n"
            f"Kellgren-Lawrence grade: {kl_grade} ({KL_LABELS[kl_grade]})\n"
            f"{context_line}\n"
            f"Guideline excerpts:\n{excerpts}\n\n"
            "Summary:"
        )

    def _fallback_synthesis(self, chunks: list[GuidelineChunk]) -> str:
        if not chunks:
            return "No matching guideline excerpts were found. " + DISCLAIMER
        bullets = "\n".join(f"- {c.heading}: {c.text.splitlines()[0]}" for c in chunks)
        return (
            "(Local LLM unavailable — showing retrieved guideline excerpts directly.)\n"
            f"{bullets}\n\n{DISCLAIMER}"
        )
